TOP ?= $(CURDIR)/../..
TMAKE_DIR ?= $(TOP)/make
include $(TMAKE_DIR)/tmake-init.mk

LIB = utils
INCS = $(wildcard include/libutils/*.h)
INCSDIR := $(INCSDIR)/libutils

include $(TMAKE_DIR)/tmake-lib.mk
