author :
  name : "tayoky"
  email : "tayoky4848@gmail.com"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

#use minima theme
remote_theme: "jekyll/minima@1fe0fbfb5347fb4e047696d3b7479c04ed0051bc"

minima:
  skin: auto
  
  nav_pages:
    - user.md
    - syscall
    - kernel.md
    - kernel/modules.md
    - todo.md

#social media link
  social_links:
    - title: "tayoky on github"
      icon: github
      url: "https://github.com/tayoky"
