# Timeout in seconds that Limine will use before automatically booting.
timeout: 10

/stanix
    protocol: limine

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    path: boot():/boot/stanix.elf
    module_path: boot():/boot/initrd.tar

/stanix (GUI)
    protocol: limine

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    cmdline: --gui
    path: boot():/boot/stanix.elf
    module_path: boot():/boot/initrd.tar

/stanix (no ACPI)
    protocol: limine

    # Path to the kernel to boot. boot():/ represents the partition on which limine.conf is located.
    path: boot():/boot/stanix.elf
    cmdline: --disable-acpi
    module_path: boot():/boot/initrd.tar