# Timeout in seconds that Limine will use before automatically booting.
timeout: 10

/Stanix
    protocol: limine
	
	cmdline: --kout=ttyboot
    path: boot():/boot/stanix.elf
    module_path: boot():/boot/initrd.tar

/Stanix (GUI)
    protocol: limine

    cmdline: --kout=ttyboot --gui
    path: boot():/boot/stanix.elf
    module_path: boot():/boot/initrd.tar

/Stanix (no ACPI)
    protocol: limine

    path: boot():/boot/stanix.elf
    cmdline: --kout=ttyboot --disable-acpi
    module_path: boot():/boot/initrd.tar

/Stanix (Screen logging)
    protocol: limine

    path: boot():/boot/stanix.elf
    cmdline: --kout=tty0
    module_path: boot():/boot/initrd.tar

/stanix (from CD)
    protocol: limine

    cmdline: --kout=ttyboot --init=/bin/initrd-init --root=/dev/cd0
    path: boot():/boot/stanix.elf
    module_path: boot():/boot/initrd.tar
