tinx_help () {
	echo "tinx [OPTIONS] ACTIONS [PACKAGES...]"
	echo "or tinx [OPTIONS] run SCRIPT [ARGUMENTS]"
	echo "options :"
	echo "--build-package : select a build tool package"
	echo "--host-package  : select a host tool package"
	echo "--redownload    : force redownload archive"
	echo "--reunpack      : force reunpack"
	echo "--reclone       : force recloning"
	echo "--reconfigure   : reconfigure the package"
	echo "--rebuild       : rebuild the package"
	echo "--reinstall     : reinstall the package"
	echo "--help          : print this help and exit"
	echo "--version       : print tinx version"
	echo "actions :"
	echo "update-cache : update tinx's cache"
	echo "get-source   : download and prepare the source for a package"
	echo "build        : build a package"
	echo "install      : install a package (by default to sysroot/build-env)"
	echo "clean-build  : clean the build directory for a package"
	echo "run          : run a command inside the tinx environement"
	echo "get-packages : get a list of packages to build for the specified packages"
}

tinx_error () {
	echo "tinx :" "$@" >&2
}

tinx_log () {
	echo "tinx :" "$@" >&2
}

tinx_setup_environ () {
	case "${1%%-packages/*}" in
		"build")
			export PREFIX="$BUILD_PREFIX"
			export TARGET="$HOST"
			export DESTDIR=""
			;;
		"host")
			export PREFIX="$HOST_PREFIX"
			export TARGET="$HOST"
			export DESTDIR="$SYSROOT"
			;;
		*)
			tinx_error "invalid package type ${1%%-packages/*}"
			return 1
			;;
	esac
	BUILD_DIR="$BUILDDIR/$1"
}

tinx_build_source_cache () {
	CACHE="$TINX_CACHE/sources"
	if ! test -d "$CACHE" ; then
		mkdir -p "$CACHE"
	fi
	echo "# automatically generated by $TINX $TINX_VERSION
CACHED_TINX_VERSION=\"$TINX_VERSION\"
CACHED_SOURCE_REVISION=\"$SOURCE_REVISION\"
CACHED_TAR=\"$TAR\"
CACHED_GIT=\"$GIT\"
CACHED_COMMIT=\"$COMMIT\"
CACHED_DIR=\"$DIR\"
" > "$CACHE/$SOURCE.sh"
}

tinx_build_dependencies_list_recur () {
	case " $VISITED " in
		*" $1 "*)
			# already visited
			return 0
			;;
	esac
	case " $VISITING " in
		*" $1 "*)
			# circular dependency
			tinx_error "circular dependency with $1"
			return 1
			;;
	esac
	VISITING="$VISITING $1"

	LOCAL_BUILD_DEPENDENCIES="$(tinx_select_package "$1" && echo "$BUILD_DEPENDENCIES")" || return 1
	for DEP in $LOCAL_BUILD_DEPENDENCIES ; do
		tinx_build_dependencies_list_recur "build-packages/$DEP" || return 1
	done
	LOCAL_DEPENDENCIES="$(tinx_select_package "$1" && echo "$DEPENDENCIES")" || return 1
	for DEP in $LOCAL_DEPENDENCIES ; do
		tinx_build_dependencies_list_recur "host-packages/$DEP" || return 1
	done

	PACKAGES_TO_DO="$PACKAGES_TO_DO $1"
	VISITED="$VISITED $1"
}

tinx_build_dependencies_list () {
	PACKAGES_TO_DO=""
	VISITING=""
	VISITED=""

	for PACKAGE in "$@" ; do
		tinx_build_dependencies_list_recur "$PACKAGE_TYPE-packages/$PACKAGE"
	done
}

tinx_build_package_cache () {
	CACHE="$TINX_CACHE/$(dirname "$1")"
	if ! test -d "$CACHE" ; then
		mkdir -p "$CACHE" || return 1
	fi

	echo "# automatically generated by $TINX $TINX_VERSION
CACHED_TINX_VERSION=\"$TINX_VERSION\"
CACHED_VERSION=\"$VERSION\"
CACHED_REVISION=\"$REVISION\"
CACHED_SOURCE=\"$SOURCE\"
CACHED_BUILD_DEPENDENCIES=\"$BUILD_DEPENDENCIES\"
CACHED_DEPENDENCIES=\"$DEPENDENCIES\"" > "$TINX_CACHE/$1.sh"
}

tinx_is_package_cache_old () {
	. "$TINX_CACHE/$1.sh" 2>/dev/null || return 0
	if test "$CACHED_VERSION" != "$VERSION" ||
	test "$CACHED_REVISION" != "$REVISION" ||
	test "$CACHED_SOURCE" != "$SOURCE" ||
	test "$CACHED_BUILD_DEPENDENCIES" != "$BUILD_DEPENDENCIES" ||
	test "$CACHED_DEPENDENCIES" != "$DEPENDENCIES" ; then
		return 0
	else
		return 1
	fi
}

tinx_select_package () {
	VERSION="unknown"
	REVISION="0"
	DEPENDENCIES=""
	BUILD_DEPENDENCIES=""
	SOURCE=""
	configure () {
		true
	}
	build () {
		make -j"$PARALLELISM"
	}
	install () {
		make install DESTDIR="$DESTDIR"
	}
	tinx_setup_environ "$1" || return 1
	if test -f "$1.sh" ; then
		. "$1.sh"
	else
		tinx_error "unknown package $1"
		return 1
	fi
	if tinx_is_package_cache_old "$1" ; then
		# things have changed
		# some stuff need to be redone
		rm -f "$BUILD_DIR/.tinx-configured"
		rm -f "$BUILD_DIR/.tinx-built"
		rm -f "$BUILD_DIR/.tinx-installed"
		tinx_build_package_cache "$1" || return 1
	elif test "$REBUILD_CACHE" = "yes" ; then
		tinx_build_package_cache "$1" || return 1
	fi
}

tinx_download () {
	if test "$#" != 2 ; then
		tinx_error "usage : tinx_download URL OUT"
		return 1
	fi
	URL="$1"
	OUT="$2"

	tinx_log "download $URL..."
	test "$DRY_RUN" = "yes" && return 0
	"$CURL" -L -o "$OUT" "$URL"
}

tinx_unpack () {
	if test "$#" != 2 ; then
		tinx_error "usage : tinx_unpack TAR OUT"
		return 1
	fi
	ARCHIVE="$1"
	OUT="$2"
	tinx_log "unpack $ARCHIVE..."
	test "$DRY_RUN" = "yes" && return 0
	
	# extract to tmp
	mkdir -p "$TMPDIR/$ARCHIVE" || return 1
	tar xf "$ARCHIVE" -C "$TMPDIR/$ARCHIVE" || return 1

	# move the child dir to main one
	rm -fr "$OUT" || return 1
	mv -T "$TMPDIR/$ARCHIVE"/*/ "$OUT" || return 1
	rm -fr "$TMPDIR/$ARCHIVE" || return 1

	return 0
}

tinx_clone_commit () {
	if test "$#" != 3 ; then
		tinx_error "usage : tinx_clone_commit GIT COMMIT OUT"
		return 1
	fi
	tinx_log "clone $1#$2..."
	test "$DRY_RUN" = "yes" && return 0
	rm -fr "$3" | return 1
	git clone --depth 1 "$1" "$3" || return 1
	git -C "$3" fetch --depth=1 origin "$2" || return 1
	git -C "$3" checkout --detach  "$2"
}

tinx_clone_tag () {
	if test "$#" != 3 ; then
		tinx_error "usage : tinx_clone_commit GIT TAG OUT"
		return 1
	fi
	tinx_log "clone $1#$2..."
	test "$DRY_RUN" = "yes" && return 0
	rm -fr "$3" | return 1
	git clone --depth 1 "$1" "$3" || return 1
	git -C "$3" fetch --depth=1 origin refs/tags/"$2":refs/tags/"$2" || return 1
	git -C "$3" checkout --detach "$2"
}

tinx_apply_patches () {
	if test -d "sources/$1/patches" ; then
		for PATCH in "$TOP/sources/$1/patches"/*.patch ; do
			tinx_log "apply $PATCH..."
			test "$DRY_RUN" = "yes" && continue
			patch -d "$SOURCE_DIR" -ruN -f -p1 -i "$PATCH" || return 1
		done
	fi
}

tinx_get_source () {
	prepare () {
		true
	}
	SOURCE_REVISION="0"
	TAR=""
	GIT=""
	COMMIT=""
	TAG=""
	DIR=""
	. "sources/$1/$1.sh"
	tinx_build_source_cache
	if test -n "$TAR" ; then
		TAR_NAME="${TAR##*/}"
		TAR_FILE="$BUILDDIR/tar/$TAR_NAME"
		SOURCE_DIR="$BUILDDIR/tar/${TAR_NAME%%.tar.*}"
		if test -d "$SOURCE_DIR" && test "$REUNPACK" = "no" ; then
			return 0
		fi
		mkdir -p "$BUILDDIR/tar"
		if ! test -f "$TAR_FILE" || test "$REDOWNLOAD" = "yes" ; then
			tinx_download "$TAR" "$TAR_FILE" || return 1
		fi
		tinx_unpack "$TAR_FILE" "$SOURCE_DIR" || return 1
	elif test -n "$GIT" ; then
		GIT_NAME="${GIT##*/}"
		SOURCE_DIR="$BUILDDIR/git/$GIT_NAME-$VERSION"
		if test -d "$SOURCE_DIR" && test "$REDOWNLOAD" = "no" ; then
			return 0
		fi
		mkdir -p "$BUILDDIR/git"
		if test -n "$COMMIT" ; then
			tinx_clone_commit "$GIT" "$COMMIT" "$SOURCE_DIR" || return 1
		elif test -n "$TAG" ; then
			tinx_clone_tag "$GIT" "$TAG" "$SOURCE_DIR" || return 1
		else
			tinx_error "no COMMIT or TAG specified for git $GIT of source $1"
			return 1
		fi
	elif test -n "$DIR" ; then
		SOURCE_DIR="$DIR"
	else
		tinx_error "no TAR GIT or DIR specified for source $1"
		return 1
	fi
	tinx_apply_patches "$1" || return 1
	test "$DRY_RUN" = "yes" && return 0
	prepare
}

tinx_configure () {
	if test -n "$SOURCE" ; then
		tinx_get_source "$SOURCE" || return 1
	fi
	if ! test -f "$BUILD_DIR/.tinx-configured" || test "$RECONFIGURE" = "yes" ; then
		tinx_log "configure $PACKAGE..."
		test "$DRY_RUN" = "yes" && return 0
		mkdir -p "$BUILD_DIR"
		(cd "$BUILD_DIR" && configure) || return 1
		touch "$BUILD_DIR/.tinx-configured"
	fi
}

tinx_build () {
	if ! test -f "$BUILD_DIR/.tinx-built" || test "$REBUILD" = "yes" ; then
		tinx_configure || return 1
		tinx_log "build $PACKAGE..."
		test "$DRY_RUN" = "yes" && return 0
		(cd "$BUILD_DIR" && build) || return 1
		touch "$BUILD_DIR/.tinx-built"
	fi
}

tinx_install () {
	if ! test -f "$BUILD_DIR/.tinx-installed" || test "$REINSTALL" = "yes" ; then
		tinx_build || return 1
		tinx_log "install $PACKAGE..."
		test "$DRY_RUN" = "yes" && return 0
		(cd "$BUILD_DIR" && install) || return 1
		touch "$BUILD_DIR/.tinx-installed"
	fi
}

tinx_clean_build () {
	rm -fr "$BUILD_DIR"
}

TINX_VERSION="v0.0.2"

: ${TINX:="$(realpath "$0")"}
: ${BUILDDIR:="$PWD/build"}
: ${TINX_CACHE:="$BUILDDIR/tinx-cache"}
: ${SYSROOT:="$BUILDDIR/sysroot"}
: ${BUILD_PREFIX:="$BUILDDIR/build-env"}
: ${HOST_PREFIX:="/usr/local"}
: ${GNU_MIRROR:="https://ftp.gnu.org"}
: ${STANIX_MIRROR:="https://github.com/tayoky"}
: ${CURL:="curl"}
: ${PARALLELISM:="$(nproc || echo 1)"}
: ${DRY_RUN:="no"}
: ${HOST:="$(uname -m)-stanix"}
: ${CFLAGS:="-Wall -Wextra -O2"}
: ${TMPDIR:=${TMP:=${TEMP:-/tmp}}}
: ${TOP:="$(dirname "$(realpath "$0")")"}

# add build tools to env
export PATH="$BUILD_PREFIX/bin:/$PATH"

export CONFIG_SUB="$PWD/config.sub"

export TINX TINX_CACHE TINX_STATE_FILE BUILDDIR SYSROOT BUILD_PREFIX CFLAGS CXXFLAGS="$CFLAGS" PREFIX
export GNU_MIRROR CURL
export PARALLELISM DRY_RUN
export HOST
export TOP

: ${CMDLINE_REDOWNLOAD:="no"}
: ${CMDLINE_REUNPACK:="no"}
: ${CMDLINE_RECONFIGURE:="no"}
: ${CMDLINE_REBUILD:="no"}
: ${CMDLINE_REINSTALL:="no"}
: ${CMDLINE_REBUILD_CACHE:="no"}
PACKAGE_TYPE="host"

for I in "$@" ; do
	case "$I" in
		--redownload|--reclone)
			CMDLINE_REDOWNLOAD=yes
			CMDLINE_REUNPACK=yes
			CMDLINE_RECONFIGURE=yes
			CMDLINE_REBUILD=yes
			CMDLINE_REINSTALL=yes
			;;
		--reunpack)
			CMDLINE_REUNPACK=yes
			CMDLINE_RECONFIGURE=yes
			CMDLINE_REBUILD=yes
			CMDLINE_REINSTALL=yes
			;;
		--reconfigure)
			CMDLINE_RECONFIGURE=yes
			CMDLINE_REBUILD=yes
			CMDLINE_REINSTALL=yes
			;;
		--reconfigure)
			CMDLINE_RECONFIGURE=yes
			CMDLINE_REBUILD=yes
			CMDLINE_REINSTALL=yes
			;;
		--rebuild)
			CMDLINE_REBUILD=yes
			CMDLINE_REINSTALL=yes
			;;
		--reinstall)
			CMDLINE_REINSTALL=yes
			;;
		--rebuild-cache)
			CMDLINE_REBUILD_CACHE=yes
			;;
		--dry-run)
			DRY_RUN=yes
			;;
		--package-type=*)
			PACKAGE_TYPE="${I##*=}"
			;;
		--build-package)
			PACKAGE_TYPE="build"
			;;
		--host-package)
			PACKAGE_TYPE="host"
			;;
		--host=*)
			HOST="${I##*=}"
			;;
		--help)
			tinx_help
			exit 0
			;;
		--version)
			echo "tinx $TINX_VERSION"
			echo "Copyright (C) 2026 Tayoky"
			exit 0
			;;
		--*)
			tinx_error "unkown option '$I'"
			exit 1
			;;
		*)
			break
			;;
	esac
	shift
done

if test -z "$1" ; then
	tinx_error "no action specified"
	exit 1
fi

ACTION="$1"
shift

if test "$ACTION" = "run" ; then
	# for compatibility with tash
	if test -n "$TASH" ; then
		"$@"
	else
		exec "$@"
	fi
	exit 1
fi

if test -z "$1" ; then
	# by default build the base package
	set -- "stanix-base"
fi

CMDLINE_PACKAGES="$@"

tinx_build_dependencies_list $CMDLINE_PACKAGES || exit 1

case "$ACTION" in
	get-packages)
		echo $PACKAGES_TO_DO
		exit 0
		;;
	get-hash)
		for PACKAGE_PATH in $PACKAGES_TO_DO ; do
			sha256sum "$TINX_CACHE/$PACKAGE_PATH.sh"
		done | sha256sum | cut -d' ' -f1
		exit 1
		;;
esac

for PACKAGE_PATH in $PACKAGES_TO_DO ; do
	PACKAGE="${PACKAGE_PATH##*-packages/}"
	case " $CMDLINE_PACKAGES " in
		*" $PACKAGE "*)
			REDOWNLOAD="$CMDLINE_REDOWNLOAD"
			REUNPACK="$CMDLINE_REUNPACK"
			RECONFIGURE="$CMDLINE_RECONFIGURE"
			REBUILD="$CMDLINE_REBUILD"
			REINSTALL="$CMDLINE_REINSTALL"
			REBUILD_CACHE="$CMDLINE_REBUILD_CACHE"
			;;
		*)
			REDOWNLOAD="no"
			REUNPACK="no"
			RECONFIGURE="no"
			REBUILD="no"
			REINSTALL="no"
			REBUILD_CACHE="no"
			;;
	esac
	tinx_select_package "$PACKAGE_PATH" || exit 1

	case "$ACTION" in
		update-cache)
			# cache already updated by tinx_select_package
			true
			;;
		get-source)
			tinx_get_source "$SOURCE" || exit 1
			;;
		configure)
			tinx_configure || exit 1
			;;
		build)
			tinx_build || exit 1
			;;
		install)
			tinx_install || exit 1
			;;
		clean|clean-build)
			tinx_clean_build || exit 1
			;;
		*)
			tinx_error "unknown action '$ACTION'"
			exit 1
			;;
	esac
done
