#ifndef MODULE_ISA_H
#define MODULE_ISA_H

#define ISA_RID_IOPORT(x) 10 + x
#define ISA_RID_IRQ(x)    20 + x

#define ISA_RID_IOPORT0 ISA_RID_IOPORT(0)
#define ISA_RID_IOPORT1 ISA_RID_IOPORT(1)
#define ISA_RID_IOPORT2 ISA_RID_IOPORT(2)
#define ISA_RID_IOPORT3 ISA_RID_IOPORT(3)
#define ISA_RID_IOPORT4 ISA_RID_IOPORT(4)
#define ISA_RID_IOPORT5 ISA_RID_IOPORT(5)
#define ISA_RID_IOPORT6 ISA_RID_IOPORT(6)
#define ISA_RID_IOPORT7 ISA_RID_IOPORT(7)

#define ISA_MAX_IOPORT 8
#define ISA_MAX_IRQ    8

#endif
