VERSION="3.4.10"
SOURCE="sdl3"
WEBSITE="https://libsdl.org/"
DEPENDENCIES="stanix-base"

configure () {
	cmake_configure \
		-DSDL_GPU=OFF \
		-DSDL_CAMERA=OFF \
		-DSDL_HAPTIC=OFF \
		-DSDL_HIDAPI=OFF \
		-DSDL_POWER=OFF \
		-DSDL_SENSOR=OFF \
		-DSDL_DIALOG=OFF \
		-DSDL_TESTS=OFF \
		-DSDL_ALSA=OFF -DSDL_JACK=OFF -DSDL_SNDIO=OFF -DSDL_PULSEAUDIO=OFF -DSDL_PIPEWIRE=OFF -DSDL_DISKAUDIO=OFF \
		-DSDL_X11=OFF -DSDL_WAYLAND=OFF -DSDL_VULKAN=OFF -DSDL_DIRECTX=OFF -DSDL_KMSDRM=OFF -DSDL_DBUS=OFF \
		-DSDL_SHARED=ON -DSDL_VENDOR_INFO="Stanix"
}
