#!/bin/sh

: ${TOP:="$(dirname "$0")/.."}

. "$TOP/scripts/stanix-package.sh"

echo "# automatically generated by $(basename "$0")
NAME=\"Stanix\"
ID=\"stanix\"
ID_LIKE=\"stanix\"
PRETTY_NAME=\"the Stanix operating system\"
HOME_URL=\"https://tayoky.github.io/stanix\"
BUG_REPORT_URL=\"https://github.com/tayoky/stanix/issues\"
VERSION_ID=\"$VERSION\"
VERSION=\"v$VERSION\""
