#!/bin/sh

set -e
PACKAGES_DIR="$BUILDDIR/packages"

# first,install every package to sysroot
"$TINX" install "$@"

for PACKAGE in "$@" ; do
	PACKAGE_DIR="$PACKAGES_DIR/$PACKAGE"
	rm -fr "$PACKAGE_DIR"
	
	mkdir -p "$PACKAGE_DIR/usr/share/tapm/"
	(
		PREFIX="$HOST_PREFIX"
		VERSION="unknown"
		WEBSITE=""
		. "$TOP/host-packages/$PACKAGE.sh"
		echo "# auto generated by $(basename "$0")
package=$PACKAGE
version=$VERSION
website=$WEBSITE
dependencies=\"$DEPENDENCIES\"" > "$PACKAGE_DIR$PREFIX/share/tapm/$PACKAGE.ini"
	)

	DESTDIR="$PACKAGE_DIR" "$TINX" --no-deps --reinstall install "$PACKAGE"

	# make the tar
	(cd "$PACKAGE_DIR" && tar -cz * -f "../$PACKAGE.tar.gz")
done
