name: run test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Build packages cache
      uses: actions/cache@v4
      with:
        path: |
          ./build/build-packages/*/.tinx-*
          ./build/build-env
          ./build/tinx-cache
        key: ${{ runner.os }}-build-v2
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Install build tools
      run: sudo apt install gettext libgmp-dev libmpc-dev libmpfr-dev bison flex texinfo nasm -y

    - name: Build
      run: ./tinx.sh install
